CREATE TABLE IF NOT EXISTS accounts (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name TEXT NOT NULL,
  server TEXT NOT NULL,
  port INTEGER NOT NULL,
  color TEXT NOT NULL DEFAULT 'blue',
  active BOOLEAN NOT NULL DEFAULT 1,
  username TEXT NOT NULL,
  mailbox TEXT NOT NULL
);